name: env_virus2_reduction
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - ipython
  - astropy=5.3
  - matplotlib>=3.7
  - numpy=1.24
  - pandas=2.0
  - scipy=1.11
  - scikit-learn=1.3
  - seaborn>=0.12
